import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar/navbar'
import Middle from '../components/content/middle'
import Footer from '../components/content/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Airdrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div id='container' className='w-[85%] h-full m-auto bg-transparent'>
        <Navbar />
        <Middle />
        <Footer />
      </div>

    </div>
  )
}
